'''
This module contains classes for representing semigroups.
'''
# pylint: disable = no-member, protected-access, invalid-name, len-as-condition

import libsemigroups
from semigroups.elements import Transformation
from semigroups.cayley_graph import CayleyGraph
from libsemigroups import ElementABC, PythonElementNC
import networkx

class Semigroup(libsemigroups.SemigroupNC):
    r'''
    A *semigroup* is a set :math:`S`, together with a binary operation :math:`*
    :S\times S\to S`, such that :math:`S` is *associative* under :math:`*`,
    that is :math:`\forall a, b, c \in S \quad a * (b * c) = (a * b) * c`.

    Let :math:`S` is a semigroup and :math:`X\subseteq S`. The *semigroup
    generated by* :math:`X` is defined as the set of all product of elements
    of :math:`X`, together with the same operation. The elements of :math:`X`
    are called the *generators*.

    This class allows semigroups generated by sets to be represented in Python.

    Args:
        args (list):   The generators of the semigroup.

    Raises:
        ValueError: If no arguments are given.

    Examples:
        >>> from semigroups import *
        >>> S = Semigroup(Transformation([1, 2, 0]),
        ... Transformation([2, 1, 0]))
        >>> # the symmetric group
        >>> S.size()
        6
        >>> Transformation([0, 1, 2]) in S
        True
        >>> Transformation([0, 1, 0]) in S
        False
        >>> # To find the generators
        >>> S[0], S[1]
        (Transformation([1, 2, 0]), Transformation([2, 1, 0]))
    '''

    def __init__(self, *args):
        if len(args) == 1 and isinstance(args[0], list):
            self.__init__(*args[0])
            return
        elif len(args) == 0:
            raise ValueError('there must be at least 1 argument')
        elif not all(map(lambda elt: isinstance(elt, type(args[0])), args)):
            raise TypeError('generators must be of the same type')

        err_msg = 'generators must have a multiplication defined on them'
        x = args[0]
        if not isinstance(x, ElementABC):
            try:
                x * x
            except:
                raise TypeError(err_msg)

        self.gens = [g if (isinstance(g, ElementABC) and str(type(g)) !=
                      "<class 'semigroups.semifp.FPSOME'>")
                else PythonElementNC(g) for g in args]
        libsemigroups.SemigroupNC.__init__(self, self.gens)
        self._done_commute_in = False

    def right_cayley_graph(self):
        r"""
        Let :math:`S` be a semigroup, generated by a set :math:`X`. Let
        :math:`G` be a directed graph with node set :math:`S`, and for any
        :math:`x, y \in S`, there is an edge from :math:`x` to :math:`y` if
        :math:`y = xz` for some :math:`z \in X`. This graph is called a *right
        Cayley graph* of :math:`S`.

        This is a function for finding the right Cayley graph of a semigroup,
        using the generating set it was defined with.

        Raises:
            TypeError: If any arguments are given.

        Returns:
            semigroups.cayley_graph.CayleyGraph: The right Cayley graph.

        Examples:
            >>> from semigroups import Semigroup
            >>> S = Semigroup(complex(0, 1))
            >>> G = S.right_cayley_graph()
            >>> G.ordered_adjacencies()
            [[1], [2], [3], [0]]
            >>> G.edges()
            [(0, 1), (1, 2), (2, 3), (3, 0)]
            >>> G.nodes()
            [0, 1, 2, 3]
        """

        G = CayleyGraph()
        G._adjacencies_list = libsemigroups.SemigroupNC.right_cayley_graph(self)
        for i, adjacencies in enumerate(G._adjacencies_list):
            G._add_node(i)
        for i, adjacencies in enumerate(G._adjacencies_list):
            for j, adj in enumerate(adjacencies):
                G._add_edge_with_label(j, (i, adj))
        return G

    def left_cayley_graph(self):
        r"""
        Let :math:`S` be a semigroup, generated by a set :math:`X`. Let
        :math:`G` be a directed graph with node set :math:`S`, and for any
        :math:`x, y \in S`, there is an edge from :math:`x` to :math:`y` if
        :math:`y = zx` for some :math:`z \in X`. This graph is called a *left
        Cayley graph* of :math:`S`.

        This is a function for finding the left Cayley graph of a semigroup,
        using the generating set it was defined with.

        Raises:
            TypeError: If any arguments are given.

        Returns:
            semigroups.cayley_graph.CayleyGraph: The left Cayley graph.

        Examples:
            >>> from semigroups import Semigroup, Transformation
            >>> S = Semigroup(Transformation([0, 0, 0]),
            ... Transformation([1, 0, 1]))
            >>> G = S.left_cayley_graph()
            >>> G.edges()
            [(0, 0), (0, 0), (1, 2), (1, 3), (2, 2), (2, 2), (3, 0), (3, 1)]
            >>> G.ordered_adjacencies()
            [[0, 0], [2, 3], [2, 2], [0, 1]]
            >>> G.strongly_connected_components()
            [set([0]), set([2]), set([1, 3])]
        """
        G = CayleyGraph()
        G._adjacencies_list = libsemigroups.SemigroupNC.left_cayley_graph(self)
        for i, adjacencies in enumerate(G._adjacencies_list):
            G._add_node(i)
        for i, adjacencies in enumerate(G._adjacencies_list):
            for j, adj in enumerate(adjacencies):
                G._add_edge_with_label(j, (i, adj))
        return G

    def commutative_semilattice_memb(self, f):
        if self.is_done():
            return f in self

        #Ensure f has same degree as elts of the generating set
        n = self.gens[0].degree()
        if f.degree() != n:
            return False
        for generator in self.gens:
            if not TCom(f, generator):
                return False

        B = [a for a in self.gens if a * f == f]
        g = f.identity()
        for a in B:
            g *= a
        return f == g

    def commutative_membership(self, f):
        r"""
        A semigroup :math:`S` is *commutative* if :math:`\forall a,b\in S\quad
        ab = ba`. This function implements a polynomial time complexity
        algorithm to test if a given transformation is in a commutative
        transformation semigroup.

        Args:
            semigroups.elements.Transformation: A transformation to test.

        Raises:
            awaeds

        Returns:
            bool: Whether or not the semigroup is commutative.

        Examples:
            >>> from semigroups import Semigroup
            >>> S = Semigroup(complex(0, 1))
            >>> G = S.right_cayley_graph()
            >>> G.ordered_adjacencies()
            [[1], [2], [3], [0]]
            >>> G.edges()
            [(0, 1), (1, 2), (2, 3), (3, 0)]
            >>> G.nodes()
            [0, 1, 2, 3]
        """
        if self.is_done():
            return f in self

     #Ensure f has same degree as elts of self.gens, the generating set
        n = self.gens[0].degree()

        if f.degree() != n:
            return False

        #Step 0
        for generator in self.gens:
            if not TCom(f, generator):
                return False

        if not self._done_commute_in:
            #Step 1
            self._states = list(range(n))

            #The SCCs of states.
            self._SCCs = bar(self._states, self.gens)
            self._no_SCCs = len(self._SCCs)

            #sources is the union of the source SCCs of states
            self._sources = set(self._states) - set([hit(a, x) for x in self._states for a in self.gens])

            #The SCCs that elements of sources lie in. Here, SCC is used to represent the
            # SCC that x is in.
            self._sourceSCCs = [SCC for SCC in self._SCCs if self._sources.intersection(set(SCC)) != set()]

            self._SCCs_wo_redundencies = sorted(list(set(self._SCCs)))

            self._bargens = [bar_dict(generator, self._SCCs) for generator in self.gens]
            no_SCCs = len(self._SCCs_wo_redundencies)
            self._bargen_Transformations = [Transformation(index_dict_function(a, self._SCCs_wo_redundencies, no_SCCs)) for a in self._bargens]


            self._done_commute_in = True

        barf = bar_dict(f, self._SCCs)
        barf_indexed = Transformation(index_dict_function(barf, self._SCCs, self._no_SCCs))

        #The image of sources under barf.
        Z = [barf[SCC] for SCC in self._sourceSCCs]

        #An abelian group when restricted to the elements whose SCCs lie in Z.
        IZ_set = set.intersection(*[stabiliser(SCC, self.gens, self._bargens, self._states) for SCC in Z] + [set([tuple(self._states)])])
        IZ = [Transformation(list(img_tup)) for img_tup in IZ_set]
        hatA = [hat(g, self._SCCs, Z, self._states) for g in IZ]

        #Step 2
        barf_indexed = Transformation(index_dict_function(barf, self._SCCs_wo_redundencies, len(self._SCCs_wo_redundencies)))
        mem_powers_of_f = aperiodic_commutative_membership_test(barf_indexed, self._bargen_Transformations)
        if not mem_powers_of_f[0]:
            return False
        g_a = Transformation(self._states)
        for a in self.gens:
            if tuple(index_dict_function(bar_dict(a, self._SCCs), self._SCCs, self._no_SCCs)) in mem_powers_of_f[1]:
                g_a *= Transformation(list(a)) ** mem_powers_of_f[1][tuple(index_dict_function(bar_dict(a, self._SCCs), self._SCCs, self._no_SCCs))]

        #Step 3
        g_a_img_list = list(g_a)
        f_img_list = list(f)
        hat_gc_dict = {}
        for i in self._sources:
            hat_gc_dict[g_a_img_list[i]] = f_img_list[i]
        for i in set(self._states) - set(hat_gc_dict.keys()):
            hat_gc_dict[i] = i
        hat_gc = Transformation(index_dict_function(hat_gc_dict, self._states, len(self._states)))

        #Step 4
        return group_mem(hat_gc, hatA + [Transformation(self._states)])

def TCom(a, b):
    n = a.degree()
    if b.degree() != n:
        return False
    for x in range(n):
        if hit(a, hit(b, x)) != hit(b, hit(a, x)):
            return False
    return True

def semi_to_trans_semi(S):
    X = list(S)
    G=[]
    for e in S.gens:
        G.append(Transformation([X.index(x * e) for x in X]))
    return Semigroup(G)

def bar(states, A):
    G = networkx.MultiDiGraph()
    for x in states:
        G.add_node(x)
    for generator in A:
        for index, image in enumerate(generator):
            G.add_edge(index, image)
    return sorted([tuple(sorted(list(x))) for x in networkx.strongly_connected_components(G)])


    #given g in a semigroup S, with a set of SCCs, where x in states is in
    #SCC SCC, we define barg to be the transformation of SCCs, such that
    #bar(xg) = (SCC)barg

def bar_dict(f, SCCs):
    #gives transformation as dictionary, with keys as input, values as image
    d = {}
    for SCC in SCCs:
        image = hit(f, SCC[0])
        for SCC2 in SCCs:
            if image in SCC2:
                d[SCC] = SCC2
                break
    return d

def group_mem(f, A):
    n = A[0].degree()
    k_i = [hit(f, 0)]
    X_i = [orbit(0, A)]
    if not k_i[0] in X_i[0][1]:
        return False, "Cows = Sheep"
    f_i = [f]

    state = 1
    while f_i[-1] != f.identity():
        X_i.append(orbit(state, A))
        k_i.append(hit(f_i[-1], state))
        f_i.append(f_i[-1] * invert_perm(prod(X_i[state][0][k_i[-1]], Transformation(list(range(n))))))

        if not k_i[-1] in X_i[-1][1]:
            return False, "Cows != Sheep", state, k_i, X_i

        state += 1

    return True


def invert_perm(f): 
    outputs = list(f)
    return Transformation([outputs.index(i) for i in range(f.degree())])


def orbit(l, A):
    X_l = {l}
    X_l_transformations = {l:()}
    for a in A:
        new1 = X_l
        new2 = X_l
        test = True
        while test:
            test = False
            new1 = set(new2)
            new2 = set()
            for x in new1:
                h = hit(a, x)
                if (not h in X_l) and (not h in new2):
                    X_l.add(h)
                    new2.add(h)
                    X_l_transformations[h] = X_l_transformations[x] + (a,)
                    test = True
            
    return X_l_transformations, X_l

#def abelian_transformation_group_membership(f, A):
#    for a in A: 
#        if not TCom(f, a):
#            return False
#    states = list(range(A[0].degree()))
#    G = networkx.MultiGraph()
#    for x in states:
#        G.add_node(x)
#    for generator in A:
#        for index, image in enumerate(generator):
#            G.add_edge(index, image)
#    orbits = sorted([tuple(sorted(list(x))) for x in networkx.connected_components(G)])
#
#    orbit_restrictions = {tuple(f): restrict_trans(f, orbits)}
#    for a in A:
#        orbit_restrictions[tuple(a)] = restrict_trans(a, orbits)
#    
#    restricted_gens = []
#    for i, j in enumerate(orbits):
#        restricted_gens.append(gens_trans_abelian_elt(orbit_restrictions[tuple(f)][i],
#                                                      [orbit_restrictions[tuple(a)][i] for a in A]))
#    b = [[restricted_gens[i].count(orbit_restrictions[tuple(a)][i]) for a in A] for i,j in enumerate(restricted_gens)]
#    t = {}
#    for i in range(len(A)):
#        for a in A:
#            t{(i,i)} = min(k s.t. g[i]**k in <gk+1 ... gr>)
#            k = 1
#            while orbit_restrictions[tuple(a)][i]
#    return b

#def gens_trans_abelian_elt(f, gens):
#    tree = [cyclic_group_list(g) for g in gens]
#    deg = gens[0].degree()
#    n = x = len(tree)
#    while x > 0:
#        x -= 1
#        current_group1 = tree[x]
#        current_group2 = []
#        if 2 * x + 1 < n:
#            for i in tree[2 * x + 1]:
#                for j in current_group1:
#                    current_group2.append([i[0] * j[0], i[1] + j[1]])
#            current_group1 = condense_list_by_1st_coordinate(current_group2)
#            current_group2 = []
#        if 2 * x < n:
#            for i in tree[2 * x]:
#                for j in current_group1:
#                    current_group2.append([i[0] * j[0], i[1] + j[1]])
#            current_group1 = condense_list_by_1st_coordinate(current_group2)
#            current_group2 = []
#        tree[x] = current_group1
#    for x in tree[0]:
#        if f == x[0]:
#            return x[1]
#    return False

#def condense_list_by_1st_coordinate(L):
#    found = []
#    out = []
#    for x in L:
#        if not x[0] in found:
#            out.append(x)
#            found.append(x[0])
#    return out

#def cyclic_group_list(g):
#    group = [[g.identity(), []]]
#    current = g
#    i = 1
#    while current != g.identity():
#        group.append([current,[g]*i])
#        i += 1
#        current *= g
#    return group


#def restrict_trans(T, S):
#    out = {}
#    for i,j in enumerate(S):
#        out[i] = Transformation(list(map(lambda x: S[i].index(x),[hit(T,x) for x in j])))
#    return out

def aperiodic_UF_commutative_membership_test(f, A):
    #luke conjectures this works but it doesn't
    thresholds = {}
    for a in A:
        old_test = a.identity()
        test = a
        i = 0
        while old_test != test:
            i += 1
            old_test = test
            test *= a
        thresholds[tuple(a)] = i
    maxthreshold = max(thresholds.values())

    i=0
    old_test = f.identity()
    test = f
    i = 0
    while old_test != test and i <= maxthreshold:
        i += 1
        old_test = test
        test *= f
    thresholds[tuple(f)] = i
    zero = A[0].identity()
    for a in A:
        zero *= a ** thresholds[tuple(a)]
    B = [A[0]]
    for a in A[1:]:
        if not aperiodic_commutative_membership_test_ir_gen(a, B, thresholds)[0]:
            B.append(a)

    return aperiodic_commutative_membership_test_ir_gen(f, B, thresholds)

def prod(L, identity):
    out = identity
    for l in L:
        out *= l
    return out

def aperiodic_commutative_membership_test_ir_gen(f, A, thresholds):
    powers = {}
    for a in A:
        j = 0
        a_power_by_f = a * f
        a_power_by_f_old = f
        while a_power_by_f_old != a_power_by_f:
            j += 1
            a_power_by_f_old = a_power_by_f
            a_power_by_f *= a
        powers[tuple(a)] = thresholds[tuple(a)] - j

    test_f = f.identity()
    for a in A:
        test_f *= a ** powers[tuple(a)]
    return test_f == f, powers

def index_dict_function(g_dict, domain, n):
    return [domain.index(g_dict[domain[i]]) for i in range(n)]

def hit(f, x):
    for i, image in enumerate(f):
        if i == x:
            return image

def stabiliser(SCC, A, bargens, states):
    return set([tuple(a) for a, barg in zip(A, bargens) if barg[SCC] == SCC]).union(set([tuple(states)]))

def hat(f, SCCs, Z, states):
    #Gives transformation as image list
    d = {}
    for SCC in SCCs:
        if SCC in Z:
            for x in SCC:
                d[x] = hit(f, x)
        else:
            for x in SCC:
                d[x] = x
    return Transformation([d[i] for i in states])

def FullTransformationMonoid(n):
    r'''
    A semigroup :math:`S` is a *moniod* if it has an *identity* element. That
    is, an element :math:`e\in S` such that :math:`ea = ae = a \quad \forall a
    \in S`.

    Let :math:`n\in\mathbb{N}`. The set of all transformations of degree
    :math:`n` forms a monoid, called the *full transformation monoid*.

    This function returns the full transformation monoid of degree :math:`n`,
    for any given :math:`n\in\mathbb{N}`.

    Args:
        n (int):    The degree of the full transformation monoid.

    Returns:
        semigroups.semigrp.Semigroup: The full transformation monoid.

    Raises:
        TypeError:  If the degree is not an int.
        ValueError: If the degree is not positive.

    Examples:
        >>> from semigroups import FullTransformationMonoid
        >>> S = FullTransformationMonoid(3)
        >>> S.size()
        27
    '''
    if not isinstance(n, int):
        raise TypeError('degree of transformation must be an int')
    if n < 1:
        raise ValueError('degree of transformation must be positive')

    if n == 1:
        return Semigroup(Transformation([0]))
    elif n == 2:
        return Semigroup(Transformation([1, 0]), Transformation([0, 0]))

    return Semigroup([Transformation([1, 0] + list(range(2, n))),
                      Transformation([0, 0] + list(range(2, n))),
                      Transformation([n - 1] + list(range(n - 1)))])

def TransDirectProduct(*args):
    assert all(isinstance(semigrp, Semigroup) for semigrp in args)
    assert all(all(isinstance(elt, Transformation) for elt in semigrp) for semigrp in args)
    length = sum(i[0].degree() for i in args)
    identity = list(range(length))
    out = [Transformation(identity)]
    usedcount = 0
    for semigroup in args:
        deg = semigroup[0].degree()
        for trans in semigroup.gens:
            new_img_list = identity[:]
            new_img_list[usedcount: usedcount + deg] = [usedcount + i for i in list(trans)]
            out.append(Transformation(new_img_list))
        usedcount += deg
    return Semigroup(out)
